$schema: "https://json-schema.org/draft/2020-12/schema"
$id: "default"

title: "Default"
description: "Default scope schema for tests"

$defs:
  reusable_subschema:
    type: "object"
    additionalProperties: false
    properties:
      property_name:
        type: "string"
        minLength: 1

type: "object"
required: []
additionalProperties: false

properties:
  settings_group:
    title: "Settings group"
    description: "A schema node to group settings under the same name"
    type: "object"
    required: ["simple_number_setting"]
    additionalProperties: false
    properties:
      simple_string_setting:
        title: "Simple string setting"
        description: "A simple nested setting of string type"
        type: "string"
        minLength: 1
        _non_standard_key: "Value of a non-standard key"
      subschema_setting:
        title: "Subschema setting"
        description: "An example of a setting that uses a subschema"
        $ref: "#/$defs/reusable_subschema"
      simple_number_setting:
        title: "Simple number setting"
        description: "A simple nested setting of number type"
        type: "number"
        default: 3.14
        minimum: 1
      simple_boolean_setting:
        title: "Simple boolean setting"
        description: "A simple nested setting of boolean type"
        type: "boolean"
        default: true
